### ISSUE TITLE
Support Cleaning Flutter/Dart Projects

### ISSUE THREAD

**Issue by virtualritz** [alexd6631/ocy#8]
See https://stackoverflow.com/questions/49279379/how-to-clear-flutters-build-cache.

**Comment by alexd6631** [comment]
Hello @virtualritz 

This was a low hanging fruit, due to the logic being very similar to other build system.

It is supported in ocy 0.1.7 by this commit bd0ad9e

**Comment by virtualritz** [comment]
Thank you so much!
